# Generated by Django 4.2.7 on 2025-09-17 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('external_organization', models.CharField(blank=True, max_length=200, verbose_name='外单位名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('staff', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_profile', to='users.staff', verbose_name='关联员工')),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='刊名')),
                ('issn', models.CharField(max_length=20, unique=True, verbose_name='ISSN')),
                ('jcr_quartile', models.CharField(blank=True, max_length=10, verbose_name='JCR分区')),
                ('impact_factor', models.FloatField(blank=True, null=True, verbose_name='影响因子')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '期刊',
                'verbose_name_plural': '期刊',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='篇名')),
                ('publication_year', models.IntegerField(verbose_name='发表年份')),
                ('unit_ranking', models.IntegerField(verbose_name='单位排名')),
                ('page_numbers', models.CharField(blank=True, max_length=50, verbose_name='页码范围')),
                ('keywords', models.CharField(blank=True, max_length=500, verbose_name='关键词')),
                ('abstract', models.TextField(blank=True, verbose_name='摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('corresponding_authors', models.ManyToManyField(related_name='corresponding_author_papers', to='achievement.author', verbose_name='通讯作者/共同通讯作者')),
                ('first_authors', models.ManyToManyField(related_name='first_author_papers', to='achievement.author', verbose_name='第一作者/共一作者')),
                ('journal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papers', to='achievement.journal', verbose_name='期刊')),
            ],
            options={
                'verbose_name': '论文',
                'verbose_name_plural': '论文',
                'ordering': ['-publication_year'],
            },
        ),
    ]
