# Generated by Django 5.0 on 2025-10-15 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='impact_factor',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='jcr_quartile',
        ),
        migrations.CreateModel(
            name='JournalMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('jcr_quartile', models.CharField(blank=True, max_length=10, verbose_name='JCR分区')),
                ('impact_factor', models.FloatField(blank=True, null=True, verbose_name='影响因子')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='achievement.journal', verbose_name='所属期刊')),
            ],
            options={
                'verbose_name': '期刊年度指标',
                'verbose_name_plural': '期刊年度指标',
                'unique_together': {('journal', 'year')},
            },
        ),
    ]
