# Generated by Django 4.2.7 on 2025-09-17 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='项目名称')),
                ('number', models.CharField(max_length=255, unique=True, verbose_name='项目编号')),
                ('funding_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='经费编号')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('status', models.CharField(choices=[('IN_PROGRESS', '在研'), ('COMPLETED', '结题'), ('TERMINATED', '终止')], default='IN_PROGRESS', max_length=20, verbose_name='项目状态')),
                ('level', models.CharField(choices=[('NATIONAL', '国家级'), ('PROVINCIAL', '省部级'), ('BASIC_RESEARCH', '基本科研业务费'), ('LOCAL_OTHER', '地方其他项目'), ('OTHER', '其他')], default='NATIONAL', max_length=20, verbose_name='项目级别')),
                ('type', models.CharField(choices=[('NATIONAL_MAJOR_SCI_TECH', '国家科技重大专项'), ('NATIONAL_BIO_BREEDING', '国家生物育种专项'), ('NATIONAL_KEY_RD', '国家重点研发计划'), ('NATIONAL_NATURAL_SCI_FUND', '国家自然科学基金'), ('SCI_TECH_INFRA_PLATFORM', '科技基础条件平台专项'), ('SCI_TECH_BASIC_WORK', '科技基础性工作专项'), ('MODERN_AGRI_IND_TECH_SYSTEM', '现代农业产业技术体系'), ('SELF_FULFILLMENT', '自有履职专项'), ('NATIONAL_MINISTERIAL_OTHER', '国家和部级其它项'), ('STANDARD_REVISION_NATIONAL', '标准制修订项目（国标）'), ('STANDARD_REVISION_INDUSTRY', '标准制修订项目（行标）'), ('STANDARD_REVISION_LOCAL', '标准制修订项目（地标）'), ('INTERNATIONAL_COOPERATION', '国际合作项目'), ('BASIC_RESEARCH_FUND', '基本科研业务费专项'), ('PROVINCIAL_PLAN', '省级计划项目'), ('LOCAL_OTHER_PROJECT', '地方其它项目'), ('OTHER_PROJECT_PLAN', '其它项目计划')], default='LOCAL_OTHER_PROJECT', max_length=30, verbose_name='项目类型')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='预算(万元)')),
                ('research_area', models.TextField(blank=True, null=True, verbose_name='研究领域')),
                ('undertake', models.CharField(choices=[('HOST', '主持'), ('PARTICIPATE', '参加')], default='HOST', max_length=20, verbose_name='承担方式')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='项目描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_projects', to='core.category', verbose_name='项目类别')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_projects', to='users.staff', verbose_name='项目负责人')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_projects', to='core.org', verbose_name='项目来源单位')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
        migrations.CreateModel(
            name='ProjectLeaderChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateField(blank=True, null=True, verbose_name='变更日期')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='变更备注')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_project_leader_changes', to='users.staff', verbose_name='新负责人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_changes', to='projects.project', verbose_name='所属项目')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='文档名称')),
                ('file', models.FileField(upload_to='project_documents/', verbose_name='文档文件')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目文档',
                'verbose_name_plural': '项目文档',
            },
        ),
        migrations.CreateModel(
            name='ProjectBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='预算项的具体名称', max_length=255, verbose_name='预算名称')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='预算金额，单位为万元', max_digits=10, null=True, verbose_name='金额(万元)')),
                ('year', models.IntegerField(blank=True, help_text='预算所属的年份', null=True, verbose_name='年度')),
                ('type', models.CharField(choices=[('INCOME', '到账经费'), ('EXPENSE', '外拨经费')], default='INCOME', help_text='预算类型：收入、支出、统筹或其他', max_length=20, verbose_name='类型')),
                ('remark', models.TextField(blank=True, help_text='关于预算项的补充说明', null=True, verbose_name='备注')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '项目预算',
                'verbose_name_plural': '项目预算',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', '成员'), ('advisor', '顾问')], default='member', max_length=20, verbose_name='角色')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('join_date', models.DateField(blank=True, null=True, verbose_name='加入时间')),
                ('leave_date', models.DateField(blank=True, null=True, verbose_name='离开日期')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='项目')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.staff', verbose_name='参与人员')),
            ],
            options={
                'verbose_name': '项目参与人员',
                'verbose_name_plural': '项目参与人员',
                'unique_together': {('project', 'staff')},
            },
        ),
    ]
