# Generated by Django 4.2.7 on 2025-08-30 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='项目名称')),
                ('number', models.CharField(max_length=255, unique=True, verbose_name='项目编号')),
                ('funding_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='经费编号')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('status', models.CharField(choices=[('APPROVED', '已立项'), ('IN_PROGRESS', '在研'), ('TERMINATED', '终止'), ('COMPLETED', '已完成')], default='APPROVED', max_length=20, verbose_name='项目状态')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='预算(万元)')),
                ('research_area', models.TextField(blank=True, null=True, verbose_name='研究领域')),
                ('undertake', models.CharField(choices=[('HOST', '主持'), ('PARTICIPATE', '参加'), ('COLLABORATE', '协作')], default='HOST', max_length=20, verbose_name='承担方式')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='项目描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_projects', to='users.staff', verbose_name='项目负责人')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_projects', to='core.org', verbose_name='项目来源单位')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_projects', to='core.category', verbose_name='项目类型')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
    ]
