# Generated by Django 5.2.7 on 2025-10-17 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='research_area',
        ),
    ]
