# Generated by Django 4.2.7 on 2025-08-31 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_projects', to='core.category', verbose_name='项目类别'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('research', '研究项目'), ('development', '开发项目'), ('consulting', '咨询项目'), ('service', '服务项目'), ('other', '其他项目')], default='other', max_length=20, verbose_name='项目类型'),
        ),
    ]
