# Generated by Django 4.2.7 on 2025-09-03 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_category_alter_project_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='预算项的具体名称', max_length=255, verbose_name='预算名称')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='预算金额，单位为万元', max_digits=10, null=True, verbose_name='金额(万元)')),
                ('year', models.IntegerField(blank=True, help_text='预算所属的年份', null=True, verbose_name='年度')),
                ('type', models.CharField(choices=[('INCOME', '收入'), ('EXPENSE', '支出'), ('COORDINATION', '统筹'), ('OTHER', '其他')], default='INCOME', help_text='预算类型：收入、支出、统筹或其他', max_length=20, verbose_name='类型')),
                ('remark', models.TextField(blank=True, help_text='关于预算项的补充说明', null=True, verbose_name='备注')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '项目预算',
                'verbose_name_plural': '项目预算',
                'ordering': ['-created_at'],
            },
        ),
    ]
