# Generated by Django 5.0 on 2025-09-12 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectbudget'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('leader', '负责人'), ('member', '成员'), ('advisor', '顾问')], default='member', max_length=20, verbose_name='角色')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('join_date', models.DateField(blank=True, null=True, verbose_name='加入时间')),
                ('leave_date', models.DateField(blank=True, null=True, verbose_name='离开日期')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='项目')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.staff', verbose_name='参与人员')),
            ],
            options={
                'verbose_name': '项目参与人员',
                'verbose_name_plural': '项目参与人员',
                'unique_together': {('project', 'staff')},
            },
        ),
    ]
