# Generated by Django 4.2.7 on 2025-09-13 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstaff',
            name='role',
            field=models.CharField(choices=[('member', '成员'), ('advisor', '顾问')], default='member', max_length=20, verbose_name='角色'),
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='文档名称')),
                ('file', models.FileField(upload_to='project_documents/', verbose_name='文档文件')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目文档',
                'verbose_name_plural': '项目文档',
            },
        ),
    ]
