# Generated by Django 5.0 on 2025-10-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '部门', 'verbose_name_plural': '部门'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': '职工', 'verbose_name_plural': '职工'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': '团队', 'verbose_name_plural': '团队'},
        ),
        migrations.AddField(
            model_name='team',
            name='research_field',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='研究领域'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
