# Generated by Django 5.0 on 2025-11-18 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '类别', 'verbose_name_plural': '类别'},
        ),
        migrations.AlterModelOptions(
            name='org',
            options={'verbose_name': '组织', 'verbose_name_plural': '组织'},
        ),
    ]
